version: '3.8'

services:
  instagram-dm:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./config:/app/config
    environment:
      - FLASK_ENV=production
      - DISPLAY=:99
    restart: unless-stopped
    # Add resource limits for stability
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G 